name: Publish to Wix with Automated Interaction and URL Capture

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Use Node.js version 18

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image from subdirectory
        run: |
          docker build -t run-wix-dev-once . -f ./.github/wix-cli-publish/Dockerfile
      - name: Run Docker image and capture output
        run: |
          docker run --rm \
            -e PUBLISH=true \
            -e WIX_SESSION2=${{ secrets.WIX_SESSION2 }} \
            -e WIX_CLI_APP_INFO=${{ secrets.WIX_CLI_APP_INFO }} \
            --memory="8192m" \
            run-wix-dev-once | tee publish_output.txt
