name: Publish to Wix with Automated Interaction and URL Capture

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Use Node.js version 18

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Attempt to pull Docker image
        id: pull-image
        run: |
          if docker pull ghcr.io/${{ github.repository }}/run-wix-dev-once:latest; then
            echo "The docker image exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "The docker image DOES NOT exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        if: ${{ steps.check-image.outputs.exists }} != 'true'
        run: |
          docker build . -t ghcr.io/${{ github.repository }}/run-wix-dev-once:latest -f ./.github/wix-cli-publish/Dockerfile
          docker push ghcr.io/${{ github.repository }}/run-wix-dev-once:latest

      - name: Run Docker image and capture output
        run: |
          docker pull ghcr.io/${{ github.repository }}/run-wix-dev-once:latest
          docker run --rm \
            -e PUBLISH=true \
            -e WIX_SESSION2=${{ secrets.WIX_SESSION2 }} \
            -e WIX_CLI_APP_INFO=${{ secrets.WIX_CLI_APP_INFO }} \
            --memory="8192m" \
            --name run-wix-dev-once \
            -d ghcr.io/${{ github.repository }}/run-wix-dev-once:latest | tee publish_output.txt
