name: Publish to Wix with Automated Interaction and URL Capture

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Use Node.js version 18

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Pull/Build+Push Docker image
        id: pull-image
        run: |
          if docker pull ghcr.io/${{ github.repository }}/run-wix-dev-once:latest; then
            echo "The docker image exists"
          else
            echo "The docker image DOES NOT exist"
            docker build . -t ghcr.io/${{ github.repository }}/run-wix-dev-once:latest -f ./.github/wix-cli-publish/Dockerfile
            docker push ghcr.io/${{ github.repository }}/run-wix-dev-once:latest
          fi

      - name: Run Docker image and capture output
        run: |
          docker pull ghcr.io/${{ github.repository }}/run-wix-dev-once:latest
          docker run --rm \
            -e PUBLISH=true \
            -e WIX_SESSION2=${{ secrets.WIX_SESSION2 }} \
            -e WIX_CLI_APP_INFO=${{ secrets.WIX_CLI_APP_INFO }} \
            --memory="8192m" \
            ghcr.io/${{ github.repository }}/run-wix-dev-once:latest | tee publish_output.txt
